---
- hosts: localhost
  connection: local

  tasks:
  - name: start an instance with a public IP address 
    amazon.aws.ec2_instance:
      name: "ansible-instance"
      key_name: "Ansible"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      network:
        assign_public_ip: true
      image_id: "{{item}}"
    loop:
      - "ami-0b982602dbb32c5bd"
      - "ami-02d26659fd82cf299"
      - "ami-02d26659fd82cf299"
