---
- hosts: localhost
  connection: local

  tasks:
  - name: start an instance with a public IP address 
    amazon.aws.ec2_instance:
      name: {{item.name}}
      key_name: "Ansible"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      network:
        assign_public_ip: true
      image_id: "{{item.image}}"
    loop:
      - {image: "ami-0b982602dbb32c5bd" , name: "manager-node-1"}
      - {image: "ami-02d26659fd82cf299" , name: "manager-node-2"}
      - {image: "ami-02d26659fd82cf299" , name: "manager-node-3" }
